<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8Iu9MbL' shared service.

return $this->privates['.service_locator.8Iu9MbL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'atendimento' => array('privates', '.errored..service_locator.8Iu9MbL.Novosga\\Entity\\Atendimento', NULL, 'Cannot autowire service ".service_locator.8Iu9MbL": it references class "Novosga\\Entity\\Atendimento" but no such service exists.'),
    'atendimentoService' => array('services', 'Novosga\\Service\\AtendimentoService', 'getAtendimentoServiceService.php', true),
    'servicoService' => array('services', 'Novosga\\Service\\ServicoService', 'getServicoServiceService.php', true),
    'translator' => array('services', 'translator', 'getTranslatorService', false),
));
