<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..HMYC0X' shared service.

return $this->privates['.service_locator..HMYC0X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'atendimento' => array('privates', '.errored..service_locator..HMYC0X.Novosga\\Entity\\Atendimento', NULL, 'Cannot autowire service ".service_locator..HMYC0X": it references class "Novosga\\Entity\\Atendimento" but no such service exists.'),
    'translator' => array('services', 'translator', 'getTranslatorService', false),
));
