<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fH12b.K' shared service.

return $this->privates['.service_locator.fH12b.K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'kernel' => array('services', 'kernel', 'getKernelService', false),
    'translator' => array('services', 'translator', 'getTranslatorService', false),
));
