<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.sebH14g' shared service.

return $this->privates['.service_locator.sebH14g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'service' => array('services', 'Novosga\\Service\\AtendimentoService', 'getAtendimentoServiceService.php', true),
));
