<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Pl.0vPk' shared service.

return $this->privates['.service_locator.Pl.0vPk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'unidade' => array('privates', '.errored..service_locator.Pl.0vPk.Novosga\\Entity\\Unidade', NULL, 'Cannot autowire service ".service_locator.Pl.0vPk": it references class "Novosga\\Entity\\Unidade" but no such service exists.'),
));
