<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1a18LS.' shared service.

return $this->privates['.service_locator.1a18LS.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'user' => array('privates', '.errored..service_locator.1a18LS..Novosga\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.1a18LS.": it references class "Novosga\\Entity\\Usuario" but no such service exists.'),
));
