<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CliF.Kk' shared service.

return $this->privates['.service_locator.CliF.Kk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'factory' => array('privates', 'security.encoder_factory.generic', 'getSecurity_EncoderFactory_GenericService.php', true),
));
