<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zbfXeeV' shared service.

return $this->privates['.service_locator.zbfXeeV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'perfil' => array('privates', '.errored..service_locator.zbfXeeV.Novosga\\Entity\\Perfil', NULL, 'Cannot autowire service ".service_locator.zbfXeeV": it references class "Novosga\\Entity\\Perfil" but no such service exists.'),
    'translator' => array('services', 'translator', 'getTranslatorService', false),
));
