<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1K9wm5x' shared service.

return $this->privates['.service_locator.1K9wm5x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'translator' => array('services', 'translator', 'getTranslatorService', false),
));
