<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Ha.jIbW.Novosga\Entity\Atendimento' shared service.

include_once $this->targetDirs[3].'/vendor/novosga/core/Entity/AbstractAtendimento.php';
include_once $this->targetDirs[3].'/vendor/novosga/core/Entity/Atendimento.php';

return $this->privates['.errored..service_locator.Ha.jIbW.Novosga\Entity\Atendimento'] = new \Novosga\Entity\Atendimento();
