<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\EventDispatcher' shared autowired service.

include_once $this->targetDirs[3].'/vendor/novosga/core/Event/EventDispatcherInterface.php';
include_once $this->targetDirs[3].'/src/Service/EventDispatcher.php';
include_once $this->targetDirs[3].'/vendor/novosga/core/Service/Configuration.php';

return $this->privates['App\Service\EventDispatcher'] = new \App\Service\EventDispatcher(($this->privates['Novosga\Service\Configuration'] ?? ($this->privates['Novosga\Service\Configuration'] = new \Novosga\Service\Configuration($this->targetDirs[3]))), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())), ($this->privates['Novosga\Infrastructure\StorageInterface'] ?? $this->load('getStorageInterfaceService.php')));
