<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Novosga\Infrastructure\StorageInterface' shared autowired service.

include_once $this->targetDirs[3].'/vendor/novosga/core/Infrastructure/StorageInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/StorageFactory.php';

return $this->privates['Novosga\Infrastructure\StorageInterface'] = (new \App\Infrastructure\StorageFactory())->createStorage(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
