<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Command\WebsocketCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/WebsocketCommand.php';
include_once $this->targetDirs[3].'/src/Service/SecurityService.php';

return $this->services['console.command.public_alias.App\Command\WebsocketCommand'] = new \App\Command\WebsocketCommand(($this->privates['App\Service\SecurityService'] ?? ($this->privates['App\Service\SecurityService'] = new \App\Service\SecurityService($this->targetDirs[3]))));
