<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.EojtYlO' shared service.

return $this->privates['.service_locator.EojtYlO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'departamento' => array('privates', '.errored..service_locator.EojtYlO.Novosga\\Entity\\Departamento', NULL, 'Cannot autowire service ".service_locator.EojtYlO": it references class "Novosga\\Entity\\Departamento" but no such service exists.'),
    'translator' => array('services', 'translator', 'getTranslatorService', false),
));
