<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3MhVG9W' shared service.

return $this->privates['.service_locator.3MhVG9W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'service' => array('services', 'Novosga\\Service\\ServicoService', 'getServicoServiceService.php', true),
    'unidade' => array('privates', '.errored..service_locator.3MhVG9W.Novosga\\Entity\\Unidade', NULL, 'Cannot autowire service ".service_locator.3MhVG9W": it references class "Novosga\\Entity\\Unidade" but no such service exists.'),
));
