<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Extensions\Doctrine\SchemaViewIgnorer' shared autowired service.

include_once $this->targetDirs[3].'/src/Extensions/Doctrine/SchemaViewIgnorer.php';

return $this->privates['App\Extensions\Doctrine\SchemaViewIgnorer'] = new \App\Extensions\Doctrine\SchemaViewIgnorer();
