<?php

namespace Proxies\__CG__\Novosga\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ServicoUnidade extends \Novosga\Entity\ServicoUnidade implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'servico', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'unidade', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'departamento', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'local', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'sigla', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'ativo', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'peso', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'prioridade', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'incremento', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'numeroInicial', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'numeroFinal', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'mensagem'];
        }

        return ['__isInitialized__', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'servico', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'unidade', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'departamento', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'local', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'sigla', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'ativo', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'peso', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'prioridade', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'incremento', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'numeroInicial', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'numeroFinal', '' . "\0" . 'Novosga\\Entity\\ServicoUnidade' . "\0" . 'mensagem'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ServicoUnidade $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getServico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServico', []);

        return parent::getServico();
    }

    /**
     * {@inheritDoc}
     */
    public function setServico(\Novosga\Entity\Servico $servico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServico', [$servico]);

        return parent::setServico($servico);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidade', []);

        return parent::getUnidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidade(\Novosga\Entity\Unidade $unidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidade', [$unidade]);

        return parent::setUnidade($unidade);
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartamento(\Novosga\Entity\Departamento $departamento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartamento', [$departamento]);

        return parent::setDepartamento($departamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamento', []);

        return parent::getDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal', []);

        return parent::getLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal(\Novosga\Entity\Local $local)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal', [$local]);

        return parent::setLocal($local);
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo(bool $ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', [$ativo]);

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function isAtivo(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAtivo', []);

        return parent::isAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeso', []);

        return parent::getPeso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeso($peso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeso', [$peso]);

        return parent::setPeso($peso);
    }

    /**
     * {@inheritDoc}
     */
    public function setSigla($sigla)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSigla', [$sigla]);

        return parent::setSigla($sigla);
    }

    /**
     * {@inheritDoc}
     */
    public function getSigla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSigla', []);

        return parent::getSigla();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrioridade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrioridade', []);

        return parent::getPrioridade();
    }

    /**
     * {@inheritDoc}
     */
    public function getIncremento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncremento', []);

        return parent::getIncremento();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroInicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroInicial', []);

        return parent::getNumeroInicial();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroFinal', []);

        return parent::getNumeroFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrioridade($prioridade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrioridade', [$prioridade]);

        return parent::setPrioridade($prioridade);
    }

    /**
     * {@inheritDoc}
     */
    public function setIncremento($incremento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncremento', [$incremento]);

        return parent::setIncremento($incremento);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroInicial($numeroInicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroInicial', [$numeroInicial]);

        return parent::setNumeroInicial($numeroInicial);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroFinal($numeroFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroFinal', [$numeroFinal]);

        return parent::setNumeroFinal($numeroFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensagem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensagem', []);

        return parent::getMensagem();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensagem($mensagem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensagem', [$mensagem]);

        return parent::setMensagem($mensagem);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
