<?php

namespace Proxies\__CG__\Novosga\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PainelSenha extends \Novosga\Entity\PainelSenha implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'servico', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'unidade', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'numeroSenha', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'siglaSenha', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'mensagem', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'local', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'numeroLocal', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'peso', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'prioridade', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'nomeCliente', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'documentoCliente'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'servico', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'unidade', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'numeroSenha', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'siglaSenha', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'mensagem', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'local', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'numeroLocal', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'peso', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'prioridade', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'nomeCliente', '' . "\0" . 'Novosga\\Entity\\PainelSenha' . "\0" . 'documentoCliente'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PainelSenha $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getServico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServico', []);

        return parent::getServico();
    }

    /**
     * {@inheritDoc}
     */
    public function setServico($servico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServico', [$servico]);

        return parent::setServico($servico);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidade', []);

        return parent::getUnidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidade($unidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidade', [$unidade]);

        return parent::setUnidade($unidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroSenha', []);

        return parent::getNumeroSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroSenha($numeroSenha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroSenha', [$numeroSenha]);

        return parent::setNumeroSenha($numeroSenha);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiglaSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiglaSenha', []);

        return parent::getSiglaSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiglaSenha($siglaSenha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiglaSenha', [$siglaSenha]);

        return parent::setSiglaSenha($siglaSenha);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensagem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensagem', []);

        return parent::getMensagem();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensagem($mensagem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensagem', [$mensagem]);

        return parent::setMensagem($mensagem);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal', []);

        return parent::getLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal($local)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal', [$local]);

        return parent::setLocal($local);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroLocal', []);

        return parent::getNumeroLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroLocal($numeroLocal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroLocal', [$numeroLocal]);

        return parent::setNumeroLocal($numeroLocal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeso', []);

        return parent::getPeso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeso($peso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeso', [$peso]);

        return parent::setPeso($peso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrioridade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrioridade', []);

        return parent::getPrioridade();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeCliente', []);

        return parent::getNomeCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoCliente', []);

        return parent::getDocumentoCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrioridade($prioridade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrioridade', [$prioridade]);

        return parent::setPrioridade($prioridade);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeCliente($nomeCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeCliente', [$nomeCliente]);

        return parent::setNomeCliente($nomeCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoCliente($documentoCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoCliente', [$documentoCliente]);

        return parent::setDocumentoCliente($documentoCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
