<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IlHP7Fc' shared service.

return $this->privates['.service_locator.IlHP7Fc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'servico' => array('privates', '.errored..service_locator.IlHP7Fc.Novosga\\Entity\\Servico', NULL, 'Cannot autowire service ".service_locator.IlHP7Fc": it references class "Novosga\\Entity\\Servico" but no such service exists.'),
    'translator' => array('services', 'translator', 'getTranslatorService', false),
    'usuario' => array('privates', '.errored..service_locator.IlHP7Fc.Novosga\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.IlHP7Fc": it references class "Novosga\\Entity\\Usuario" but no such service exists.'),
));
