<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6mSGIPj' shared service.

return $this->privates['.service_locator.6mSGIPj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'logger' => array('privates', 'monolog.logger', 'getMonolog_LoggerService', false),
    'service' => array('services', 'Novosga\\Service\\AtendimentoService', 'getAtendimentoServiceService.php', true),
));
