<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Sb0I667' shared service.

return $this->privates['.service_locator.Sb0I667'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'atendimentoService' => array('services', 'Novosga\\Service\\AtendimentoService', 'getAtendimentoServiceService.php', true),
    'filaService' => array('services', 'Novosga\\Service\\FilaService', 'getFilaServiceService.php', true),
    'translator' => array('services', 'translator', 'getTranslatorService', false),
    'usuarioService' => array('services', 'Novosga\\Service\\UsuarioService', 'getUsuarioServiceService.php', true),
));
