<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VioBoaM' shared service.

return $this->privates['.service_locator.VioBoaM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'usuarioService' => array('services', 'Novosga\\Service\\UsuarioService', 'getUsuarioServiceService.php', true),
));
