<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Novosga\Service\AtendimentoService' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\novosga\\core\\Service\\StorageAwareService.php';
include_once $this->targetDirs[3].'\\vendor\\novosga\\core\\Service\\AtendimentoService.php';

return $this->services['Novosga\Service\AtendimentoService'] = new \Novosga\Service\AtendimentoService(($this->privates['Novosga\Infrastructure\StorageInterface'] ?? $this->load('getStorageInterfaceService.php')), ($this->privates['App\Service\EventDispatcher'] ?? $this->load('getEventDispatcher2Service.php')), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), ($this->services['translator'] ?? $this->getTranslatorService()));
