<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Novosga\ReportsBundle\Form\ChartType' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\modules\\novosga\\reports-bundle\\Form\\ChartType.php';

return $this->privates['Novosga\ReportsBundle\Form\ChartType'] = new \Novosga\ReportsBundle\Form\ChartType(($this->services['translator'] ?? $this->getTranslatorService()));
