<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_oauth_server.authorize.form' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\ClearableErrorsInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\Form.php';

return $this->services['fos_oauth_server.authorize.form'] = ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php'))->createNamed('fos_oauth_server_authorize_form', 'FOS\\OAuthServerBundle\\Form\\Type\\AuthorizeFormType', NULL, array('validation_groups' => $this->parameters['fos_oauth_server.authorize.form.validation_groups']));
