<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.O9PQj_0.Novosga\Entity\Local' shared service.

include_once $this->targetDirs[3].'\\vendor\\novosga\\core\\Entity\\Local.php';

return $this->privates['.errored..service_locator.O9PQj_0.Novosga\Entity\Local'] = new \Novosga\Entity\Local();
