<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.tPO8_2J.App\Entity\OAuthClient' shared service.

include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth2-php\\lib\\Model\\IOAuth2Client.php';
include_once $this->targetDirs[3].'\\vendor\\novosga\\oauth-server-bundle\\Model\\ClientInterface.php';
include_once $this->targetDirs[3].'\\vendor\\novosga\\oauth-server-bundle\\Model\\Client.php';
include_once $this->targetDirs[3].'\\vendor\\novosga\\oauth-server-bundle\\Entity\\Client.php';
include_once $this->targetDirs[3].'\\src\\Entity\\OAuthClient.php';

return $this->privates['.errored..service_locator.tPO8_2J.App\Entity\OAuthClient'] = new \App\Entity\OAuthClient();
