<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.5kAHkxz.Novosga\Entity\Servico' shared service.

include_once $this->targetDirs[3].'\\vendor\\novosga\\core\\Entity\\Servico.php';

return $this->privates['.errored..service_locator.5kAHkxz.Novosga\Entity\Servico'] = new \Novosga\Entity\Servico();
