<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.encoder_factory.generic' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\Encoder\\EncoderFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\Encoder\\EncoderFactory.php';

return $this->privates['security.encoder_factory.generic'] = new \Symfony\Component\Security\Core\Encoder\EncoderFactory(array('bcrypt' => array('class' => 'Symfony\\Component\\Security\\Core\\Encoder\\BCryptPasswordEncoder', 'arguments' => array(0 => 12)), 'md5' => array('algorithm' => 'md5', 'encode_as_base64' => false, 'iterations' => 1, 'hash_algorithm' => 'sha512', 'key_length' => 40, 'ignore_case' => false, 'cost' => 13, 'memory_cost' => NULL, 'time_cost' => NULL, 'threads' => NULL)));
