<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.IlHP7Fc.Novosga\Entity\Usuario' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\User\\UserInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\User\\AdvancedUserInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\User\\EquatableInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\Encoder\\EncoderAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\novosga\\core\\Entity\\Usuario.php';

return $this->privates['.errored..service_locator.IlHP7Fc.Novosga\Entity\Usuario'] = new \Novosga\Entity\Usuario();
