<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Pl.0vPk.Novosga\Entity\Unidade' shared service.

include_once $this->targetDirs[3].'\\vendor\\novosga\\core\\Entity\\Unidade.php';

return $this->privates['.errored..service_locator.Pl.0vPk.Novosga\Entity\Unidade'] = new \Novosga\Entity\Unidade();
