<?php

// This file has been auto-generated by the Symfony Cache Component.

return array(array(

'App_Entity_NovaSenha' => 0,
'Novosga_Entity_AbstractAtendimento' => 1,
'Novosga_Entity_AbstractAtendimentoCodificado' => 2,
'Novosga_Entity_Agendamento' => 3,
'Novosga_Entity_Atendimento' => 4,
'Novosga_Entity_AtendimentoCodificado' => 5,
'Novosga_Entity_AtendimentoCodificadoHistorico' => 6,
'Novosga_Entity_AtendimentoHistorico' => 7,
'Novosga_Entity_Cliente' => 8,
'Novosga_Entity_Departamento' => 9,
'Novosga_Entity_Local' => 10,
'Novosga_Entity_Lotacao' => 11,
'Novosga_Entity_Perfil' => 12,
'Novosga_Entity_Prioridade' => 13,
'Novosga_Entity_Servico' => 14,
'Novosga_Entity_Unidade' => 15,
'Novosga_Entity_Usuario' => 16,

), array(

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\NovaSenha',
                    'unidade',
                    'prioridade',
                    'servico',
                    'cliente',
                    'metadata',
                ],
                'attributesMetadata' => [
                    [
                        'unidade' => $o[1],
                        'prioridade' => $o[2],
                        'servico' => $o[3],
                        'cliente' => $o[4],
                        'metadata' => $o[5],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\AbstractAtendimento',
                    'id',
                    'unidade',
                    'servico',
                    'usuario',
                    'usuarioTriagem',
                    'local',
                    'prioridade',
                    'dataAgendamento',
                    'dataChegada',
                    'dataChamada',
                    'dataInicio',
                    'dataFim',
                    'tempoEspera',
                    'tempoPermanencia',
                    'tempoAtendimento',
                    'tempoDeslocamento',
                    'status',
                    'resolucao',
                    'cliente',
                    'senha',
                    'pai',
                    'observacao',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'unidade' => $o[2],
                        'servico' => $o[3],
                        'usuario' => $o[4],
                        'usuarioTriagem' => $o[5],
                        'local' => $o[6],
                        'prioridade' => $o[7],
                        'dataAgendamento' => $o[8],
                        'dataChegada' => $o[9],
                        'dataChamada' => $o[10],
                        'dataInicio' => $o[11],
                        'dataFim' => $o[12],
                        'tempoEspera' => $o[13],
                        'tempoPermanencia' => $o[14],
                        'tempoAtendimento' => $o[15],
                        'tempoDeslocamento' => $o[16],
                        'status' => $o[17],
                        'resolucao' => $o[18],
                        'cliente' => $o[19],
                        'senha' => $o[20],
                        'pai' => $o[21],
                        'observacao' => $o[22],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\AbstractAtendimentoCodificado',
                    'servico',
                    'peso',
                    'atendimento',
                ],
                'attributesMetadata' => [
                    [
                        'servico' => $o[1],
                        'peso' => $o[2],
                        'atendimento' => $o[3],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Agendamento',
                    'id',
                    'data',
                    'hora',
                    'cliente',
                    'unidade',
                    'servico',
                    'dataConfirmacao',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'data' => $o[2],
                        'hora' => $o[3],
                        'cliente' => $o[4],
                        'unidade' => $o[5],
                        'servico' => $o[6],
                        'dataConfirmacao' => $o[7],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Atendimento',
                    'codificados',
                    'id',
                    'unidade',
                    'servico',
                    'usuario',
                    'usuarioTriagem',
                    'local',
                    'dataAgendamento',
                    'dataChegada',
                    'dataChamada',
                    'status',
                    'resolucao',
                    'cliente',
                    'senha',
                    'pai',
                    'observacao',
                    'h',
                    'prioridade',
                    'dataInicio',
                    'dataFim',
                    'tempoEspera',
                    'tempoPermanencia',
                    'tempoAtendimento',
                    'tempoDeslocamento',
                ],
                'attributesMetadata' => [
                    [
                        'codificados' => $o[1],
                        'id' => $o[2],
                        'unidade' => $o[3],
                        'servico' => $o[4],
                        'usuario' => $o[5],
                        'usuarioTriagem' => $o[6],
                        'local' => $o[7],
                        'dataAgendamento' => $o[8],
                        'dataChegada' => $o[9],
                        'dataChamada' => $o[10],
                        'status' => $o[11],
                        'resolucao' => $o[12],
                        'cliente' => $o[13],
                        'senha' => $o[14],
                        'pai' => $o[15],
                        'observacao' => $o[16],
                        'h' => $o[17],
                        'prioridade' => $o[18],
                        'dataInicio' => $o[19],
                        'dataFim' => $o[20],
                        'tempoEspera' => $o[21],
                        'tempoPermanencia' => $o[22],
                        'tempoAtendimento' => $o[23],
                        'tempoDeslocamento' => $o[24],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\AtendimentoCodificado',
                    'atendimento',
                    'servico',
                    'peso',
                ],
                'attributesMetadata' => [
                    [
                        'atendimento' => $o[1],
                        'servico' => $o[2],
                        'peso' => $o[3],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\AtendimentoCodificadoHistorico',
                    'atendimento',
                    'servico',
                    'peso',
                ],
                'attributesMetadata' => [
                    [
                        'atendimento' => $o[1],
                        'servico' => $o[2],
                        'peso' => $o[3],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\AtendimentoHistorico',
                    'codificados',
                    'id',
                    'unidade',
                    'servico',
                    'usuario',
                    'usuarioTriagem',
                    'local',
                    'dataAgendamento',
                    'dataChegada',
                    'dataChamada',
                    'status',
                    'resolucao',
                    'cliente',
                    'senha',
                    'pai',
                    'observacao',
                    'prioridade',
                    'dataInicio',
                    'dataFim',
                    'tempoEspera',
                    'tempoPermanencia',
                    'tempoAtendimento',
                    'tempoDeslocamento',
                ],
                'attributesMetadata' => [
                    [
                        'codificados' => $o[1],
                        'id' => $o[2],
                        'unidade' => $o[3],
                        'servico' => $o[4],
                        'usuario' => $o[5],
                        'usuarioTriagem' => $o[6],
                        'local' => $o[7],
                        'dataAgendamento' => $o[8],
                        'dataChegada' => $o[9],
                        'dataChamada' => $o[10],
                        'status' => $o[11],
                        'resolucao' => $o[12],
                        'cliente' => $o[13],
                        'senha' => $o[14],
                        'pai' => $o[15],
                        'observacao' => $o[16],
                        'prioridade' => $o[17],
                        'dataInicio' => $o[18],
                        'dataFim' => $o[19],
                        'tempoEspera' => $o[20],
                        'tempoPermanencia' => $o[21],
                        'tempoAtendimento' => $o[22],
                        'tempoDeslocamento' => $o[23],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Cliente',
                    'id',
                    'nome',
                    'documento',
                    'email',
                    'telefone',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'nome' => $o[2],
                        'documento' => $o[3],
                        'email' => $o[4],
                        'telefone' => $o[5],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Departamento',
                    'id',
                    'nome',
                    'descricao',
                    'ativo',
                    'createdAt',
                    'updatedAt',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'nome' => $o[2],
                        'descricao' => $o[3],
                        'ativo' => $o[4],
                        'createdAt' => $o[5],
                        'updatedAt' => $o[6],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Local',
                    'id',
                    'nome',
                    'createdAt',
                    'updatedAt',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'nome' => $o[2],
                        'createdAt' => $o[3],
                        'updatedAt' => $o[4],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Lotacao',
                    'id',
                    'usuario',
                    'unidade',
                    'perfil',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'usuario' => $o[2],
                        'unidade' => $o[3],
                        'perfil' => $o[4],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Perfil',
                    'id',
                    'nome',
                    'descricao',
                    'modulos',
                    'createdAt',
                    'updatedAt',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'nome' => $o[2],
                        'descricao' => $o[3],
                        'modulos' => $o[4],
                        'createdAt' => $o[5],
                        'updatedAt' => $o[6],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
13 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Prioridade',
                    'id',
                    'nome',
                    'descricao',
                    'peso',
                    'ativo',
                    'createdAt',
                    'updatedAt',
                    'deletedAt',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'nome' => $o[2],
                        'descricao' => $o[3],
                        'peso' => $o[4],
                        'ativo' => $o[5],
                        'createdAt' => $o[6],
                        'updatedAt' => $o[7],
                        'deletedAt' => $o[8],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
14 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Servico',
                    'id',
                    'nome',
                    'descricao',
                    'ativo',
                    'peso',
                    'mestre',
                    'subServicos',
                    'servicosUnidade',
                    'createdAt',
                    'updatedAt',
                    'deletedAt',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'nome' => $o[2],
                        'descricao' => $o[3],
                        'ativo' => $o[4],
                        'peso' => $o[5],
                        'mestre' => $o[6],
                        'subServicos' => $o[7],
                        'servicosUnidade' => $o[8],
                        'createdAt' => $o[9],
                        'updatedAt' => $o[10],
                        'deletedAt' => $o[11],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
15 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Unidade',
                    'id',
                    'nome',
                    'descricao',
                    'ativo',
                    'impressao',
                    'createdAt',
                    'updatedAt',
                    'deletedAt',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'nome' => $o[2],
                        'descricao' => $o[3],
                        'ativo' => $o[4],
                        'impressao' => $o[5],
                        'createdAt' => $o[6],
                        'updatedAt' => $o[7],
                        'deletedAt' => $o[8],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
16 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Serializer\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\ClassMetadata')),
            clone ($p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata')),
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
            clone $p['Symfony\\Component\\Serializer\\Mapping\\AttributeMetadata'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Novosga\\Entity\\Usuario',
                    'id',
                    'login',
                    'nome',
                    'sobrenome',
                    'email',
                    'senha',
                    'ativo',
                    'ultimoAcesso',
                    'ip',
                    'sessionId',
                    'lotacoes',
                    'lotacao',
                    'admin',
                    'algorithm',
                    'salt',
                    'roles',
                    'createdAt',
                    'updatedAt',
                    'deletedAt',
                    'nomeCompleto',
                    'accountNonExpired',
                    'accountNonLocked',
                    'credentialsNonExpired',
                    'enabled',
                    'password',
                    'username',
                    'encoderName',
                    'equalTo',
                ],
                'attributesMetadata' => [
                    [
                        'id' => $o[1],
                        'login' => $o[2],
                        'nome' => $o[3],
                        'sobrenome' => $o[4],
                        'email' => $o[5],
                        'senha' => $o[6],
                        'ativo' => $o[7],
                        'ultimoAcesso' => $o[8],
                        'ip' => $o[9],
                        'sessionId' => $o[10],
                        'lotacoes' => $o[11],
                        'lotacao' => $o[12],
                        'admin' => $o[13],
                        'algorithm' => $o[14],
                        'salt' => $o[15],
                        'roles' => $o[16],
                        'createdAt' => $o[17],
                        'updatedAt' => $o[18],
                        'deletedAt' => $o[19],
                        'nomeCompleto' => $o[20],
                        'accountNonExpired' => $o[21],
                        'accountNonLocked' => $o[22],
                        'credentialsNonExpired' => $o[23],
                        'enabled' => $o[24],
                        'password' => $o[25],
                        'username' => $o[26],
                        'encoderName' => $o[27],
                        'equalTo' => $o[28],
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},

));
