<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA2Ef9ip\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA2Ef9ip/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA2Ef9ip.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA2Ef9ip\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA2Ef9ip\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'A2Ef9ip',
    'container.build_id' => '551efdb1',
    'container.build_time' => 1634584736,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerA2Ef9ip');
